service: deno-test

frameworkVersion: "^3"

useDotenv: true

provider:
  apiGateway:
    shouldStartNameWithService: true
  architecture: arm64
  deploymentMethod: direct
  httpApi:
    cors: true
  logRetentionInDays: 90
  name: aws
  region: ap-northeast-1
  stackName: ${self:service}-${sls:stage}
  timeout: 59
  versionFunctions: false

functions:
  greet:
    ecrImage:
      path: functions/greeter
      platform: linux/arm64
      provenance: false

package:
  individually: true

plugins:
  - serverless-function-image

custom:
  enterprise:
    collectLambdaLogs: false
    disableAwsSpans: true
    disableHttpSpans: true
  safeguards:
    isDisabled: true
